name: Codecov
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: Build on java ${{ matrix.java }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        java: ['8']
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
